import { LegalShell, LegalSection } from "./legal-shell";

/**
 * Aria Terms of Service. Covers the real shape of the product: a client for
 * GitHub (which has its own terms), AI-generated suggestions that are never
 * auto-applied, and Stripe subscriptions. Replace placeholder contact
 * details before launch.
 */
export default function Terms() {
  return (
    <LegalShell title="Terms of Service" updated="August 14, 2026">
      <LegalSection heading="The service">
        <p>
          Aria is a browser-based workspace for working with code hosted on
          GitHub. You connect your GitHub account and use Aria to browse,
          edit, commit, and manage pull requests on repositories you have
          permission to access.
        </p>
        <p>
          Aria is a client: the repositories, branches, and commits you work
          with are governed by GitHub's terms of service and by the terms of
          each repository you touch. We do not host your repositories.
        </p>
      </LegalSection>

      <LegalSection heading="Your account">
        <p>
          You're responsible for keeping your account credentials safe and for
          everything done through your account. You must be at least 13 years
          old (16 in the EU/UK) and must not use the service to violate any
          law or any repository's license.
        </p>
        <p>
          Don't use Aria to spam, probe, or attack other systems, to commit
          content you don't have the right to commit, or to upload malware or
          other harmful code.
        </p>
      </LegalSection>

      <LegalSection heading="AI assistance">
        <p>
          Aria's assistant can suggest edits, commit messages, and conflict
          resolutions. Suggestions are generated by an AI model and may be
          incorrect, incomplete, or inappropriate. Nothing is ever applied
          automatically — you review and confirm every change before it
          touches your repository.
        </p>
        <p>
          You are responsible for reviewing AI-suggested code before
          committing it, including for security, licensing, and correctness.
        </p>
      </LegalSection>

      <LegalSection heading="Subscriptions and payments">
        <p>
          Aria is free to use with limited features. Paid plans are billed in
          advance through Stripe on a recurring basis until cancelled. You can
          cancel anytime from the billing portal; access continues until the
          end of the paid period, after which the account returns to the free
          plan.
        </p>
        <p>
          Prices are shown at checkout and may change for future billing
          periods with notice. Refunds are at our discretion, consistent with
          applicable law.
        </p>
      </LegalSection>

      <LegalSection heading="Our intellectual property">
        <p>
          The Aria software, design, and branding are owned by us and licensed,
          not sold. You may not copy, resell, or reverse-engineer the service.
          Your code, repositories, and drafts remain yours.
        </p>
      </LegalSection>

      <LegalSection heading="Disclaimers and liability">
        <p>
          The service is provided "as is" without warranties of any kind —
          including that it will be uninterrupted, error-free, or that
          automated operations will preserve your data. You're responsible for
          backing up important work; drafts are a convenience, not a backup
          guarantee.
        </p>
        <p>
          To the maximum extent permitted by law, our total liability for any
          claim arising out of the service is limited to the amount you paid
          us in the twelve months before the claim. Nothing in these terms
          limits liability that cannot be limited by law.
        </p>
      </LegalSection>

      <LegalSection heading="Termination">
        <p>
          You can stop using Aria at any time. We may suspend or terminate
          access for violations of these terms, abusive use, or as required
          by law.
        </p>
      </LegalSection>

      <LegalSection heading="Changes and contact">
        <p>
          We may update these terms; material changes will be announced in the
          app. Questions? Contact{" "}
          <a
            href="mailto:legal@arialabs.dev"
            className="underline underline-offset-2"
          >
            legal@arialabs.dev
          </a>{" "}
          or write to Aria Labs (Karan Kotwal), 2825 Azad Nagar, Ranjhi,
          Jabalpur, Madhya Pradesh 482005, India.
        </p>
        <p>
          These terms are governed by the laws of India (Jabalpur, Madhya
          Pradesh), where Aria Labs operates, except where mandatory law in
          your jurisdiction of residence applies.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
